services:
  neko-manager:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".data:/.data"
      - ".env:/.env"

  nginx:
    image: nginx:1.29.4-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
